[package]
name = "rustground"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
axum = "0.6.6"
clap = { version = "4.1.4", features = ["derive"] }
crates_io_api = "0.8.1"
env_logger = "0.10.0"
log = "0.4.17"
redis = "0.22.3"
serde_json = "1.0.93"
